EdufaceCms.UI/Controllers/BranchController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using EdufaceCms.Entities.Concrete;
using EdufaceCms.BusinessLayer.Managers.EntityFramework.Abstract;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace EdufaceCms.UI.Controllers
{
    [Authorize(Roles = "Admin")]
    public class BranchController : BaseController
    {
        private readonly IBranchRepository _branchRepo;
        private readonly UserManager<UserEntity> _userManager;

        public BranchController(IBranchRepository branchRepo, UserManager<UserEntity> userManager) : base(userManager)
        {
            _userManager = userManager;
            _branchRepo=branchRepo;
            PageSubTitle = "Şubeler";
        }

        // GET: BranchEntities
        public async Task<IActionResult> Index()
        {
            return View(await _branchRepo.GetListAsync());
        }

        // GET: BranchEntities/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var branchEntity = await _branchRepo
                .GetAsync(m => m.Id == id);
            if (branchEntity == null)
            {
                return NotFound();
            }

            return View(branchEntity);
        }

        // GET: BranchEntities/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: BranchEntities/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Phone,Address,Id,IsActive,CreDate")] BranchEntity branchEntity)
        {
            if (ModelState.IsValid)
            {
                await _branchRepo.AddAsync(branchEntity);
                return RedirectToAction(nameof(Index));
            }
            return View(branchEntity);
        }

        // GET: BranchEntities/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var branchEntity = await _branchRepo.GetAsync(x=>x.Id==id);
            if (branchEntity == null)
            {
                return NotFound();
            }
            return View(branchEntity);
        }

        // POST: BranchEntities/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Name,Phone,Address,Id,IsActive")] BranchEntity branchEntity)
        {
            if (id != branchEntity.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _branchRepo.UpdateAsync(branchEntity);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BranchEntityExists(branchEntity.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(branchEntity);
        }

        // GET: BranchEntities/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var branchEntity = await _branchRepo
                .GetAsync(m => m.Id == id);
            if (branchEntity == null)
            {
                return NotFound();
            }

            return View(branchEntity);
        }

        // POST: BranchEntities/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var branchEntity = await _branchRepo.GetAsync(x=>x.Id==id);

            await _branchRepo.DeleteAsync(branchEntity);
            return RedirectToAction(nameof(Index));
        }

        private bool BranchEntityExists(int id)
        {
            return _branchRepo.IsAny(x=>x.Id==id);
        }
    }
}

EdufaceCms.UI/Controllers/LevelController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using EdufaceCms.Entities.Concrete;
using EdufaceCms.BusinessLayer.Managers.EntityFramework.Abstract;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace EdufaceCms.UI.Controllers
{
    [Authorize(Roles = "Admin")]
    public class LevelController : BaseController
    {
        private readonly ILevelRepository _levelRepository;
        private readonly UserManager<UserEntity> _userManager;

        public LevelController(ILevelRepository levelRepository, UserManager<UserEntity> userManager) : base(userManager)
        {
            _userManager = userManager;
            _levelRepository = levelRepository;
            PageSubTitle = "Seviyeler";
        }


        // GET: Level
        public async Task<IActionResult> Index()
        {
            return View(await _levelRepository.GetListAsync());
        }

        // GET: Level/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var levelEntity = await _levelRepository
                .GetAsync(m => m.Id == id);
            if (levelEntity == null)
            {
                return NotFound();
            }

            return View(levelEntity);
        }

        // GET: Level/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Level/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Id")] LevelEntity levelEntity)
        {
            if (ModelState.IsValid)
            {
                await _levelRepository.AddAsync(levelEntity);
                return RedirectToAction(nameof(Index));
            }
            return View(levelEntity);
        }

        // GET: Level/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var levelEntity = await _levelRepository.GetAsync(x=>x.Id==id);
            if (levelEntity == null)
            {
                return NotFound();
            }
            return View(levelEntity);
        }

        // POST: Level/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Name,Id,IsActive,CreDate")] LevelEntity levelEntity)
        {
            if (id != levelEntity.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _levelRepository.UpdateAsync(levelEntity);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LevelEntityExists(levelEntity.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(levelEntity);
        }

        // GET: Level/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var levelEntity = await _levelRepository
                .GetAsync(m => m.Id == id);
            if (levelEntity == null)
            {
                return NotFound();
            }

            return View(levelEntity);
        }

        // POST: Level/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var levelEntity = await _levelRepository.GetAsync(x=>x.Id==id);
            await _levelRepository.DeleteAsync(levelEntity);
            return RedirectToAction(nameof(Index));
        }

        private bool LevelEntityExists(int id)
        {
            return _levelRepository.IsAny(e => e.Id == id);
        }
    }
}

EdufaceCms.UI/Controllers/TimeController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using EdufaceCms.Entities.Concrete;
using EdufaceCms.BusinessLayer.Managers.EntityFramework.Abstract;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace EdufaceCms.UI.Controllers
{
    [Authorize(Roles = "Admin")]
    public class TimeController : BaseController
    {
        private readonly ITimeRepository _timeRepository;
        private readonly UserManager<UserEntity> _userManager;

        public TimeController(ITimeRepository timeRepository, UserManager<UserEntity> userManager) : base(userManager)
        {
            _userManager = userManager;
            _timeRepository = timeRepository;
            PageSubTitle = "Ders Saatleri";
        }

        // GET: Time
        public async Task<IActionResult> Index()
        {
            return View(await _timeRepository.GetListAsync());
        }

        // GET: Time/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var timeEntity = await _timeRepository
                .GetAsync(m => m.Id == id);
            if (timeEntity == null)
            {
                return NotFound();
            }

            return View(timeEntity);
        }

        // GET: Time/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Time/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Id")] TimeEntity timeEntity)
        {
            if (ModelState.IsValid)
            {
                await _timeRepository.AddAsync(timeEntity);
                return RedirectToAction(nameof(Index));
            }
            return View(timeEntity);
        }

        // GET: Time/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var timeEntity = await _timeRepository.GetAsync(x=>x.Id==id);
            if (timeEntity == null)
            {
                return NotFound();
            }
            return View(timeEntity);
        }

        // POST: Time/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Name,Id,IsActive,CreDate")] TimeEntity timeEntity)
        {
            if (id != timeEntity.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _timeRepository.UpdateAsync(timeEntity);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TimeEntityExists(timeEntity.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(timeEntity);
        }

        // GET: Time/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var timeEntity = await _timeRepository
                .GetAsync(m => m.Id == id);
            if (timeEntity == null)
            {
                return NotFound();
            }

            return View(timeEntity);
        }

        // POST: Time/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var timeEntity = await _timeRepository.GetAsync(x=>x.Id==id);
            await _timeRepository.DeleteAsync(timeEntity);
            return RedirectToAction(nameof(Index));
        }

        private bool TimeEntityExists(int id)
        {
            return _timeRepository.IsAny(e => e.Id == id);
        }
    }
}

EdufaceCms.UI/Controllers/UserController.cs
using System.Threading.Tasks;
using EdufaceCms.Entities.Concrete;
using EdufaceCms.UI.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace EdufaceCms.UI.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UserController : BaseController
    {
        private readonly IPasswordHasher<UserEntity> _passwordHasher;
        private readonly UserManager<UserEntity> _userManager;
        private SignInManager<UserEntity> _signInManager;
        public UserController(UserManager<UserEntity> userManager, IPasswordHasher<UserEntity> passwordHasher, SignInManager<UserEntity> signInManager) : base(userManager)
        {
            _userManager = userManager;
            _passwordHasher = passwordHasher;
            _signInManager = signInManager;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Settings()
        {
            var user = await CurrentUser;
            var model = new SettingModel
            {
                Username = user.UserName,
                Password = user.PasswordHash,
                Email = user.Email
            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Settings(SettingModel settingModel)
        {
            if (!ModelState.IsValid) return View(settingModel);

            var user = await CurrentUser;
            var hashPass = _passwordHasher.HashPassword(user, settingModel.Password);
            user.PasswordHash = hashPass;
            await _userManager.UpdateAsync(user);

            return View(settingModel);
        }
        public async Task<IActionResult> LogOut()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }
    }
}

EdufaceCms.UI/Views/Shared/Layouts/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
        @ViewData["Title"] - Eduface Cms

    </title>

    <!-- Custom fonts for this template-->
    <link href="~/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <!-- Custom styles for this template-->
    <link href="~/css/sb-admin-2.min.css" rel="stylesheet">

</head>
<body id="page-top">
    <!-- Page Wrapper -->
    <div id="wrapper">
        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" asp-controller="Home" asp-action="Index">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-laugh-wink"></i>
                </div>
                <div class="sidebar-brand-text mx-3">EDUFace Admin <!--<sup>2</sup>--></div>
            </a>
            <!-- Divider -->
            <hr class="sidebar-divider my-0">
            <!-- Nav Item - Dashboard -->
            <li class="nav-item active">
                <a class="nav-link" asp-controller="Home" asp-action="Index">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Anasayfa</span>
                </a>
            </li>
            <!-- Divider -->
            <hr class="sidebar-divider">
            <!-- Heading -->
            <div class="sidebar-heading">
                Interface
            </div>

            <li class="nav-item">
                <a asp-controller="PreRegister" asp-action="Index" class="nav-link">
                    <i class="fas fa-fw fa-registered"></i>
                    <span>Ön Kayıt</span>
                </a>
            </li>

            @{ if (User.IsInRole("Admin"))
                {
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Branch" asp-action="Index">
                            <i class="fas fa-fw fa-table"></i>
                            <span>Şubeler</span>
                        </a>
                    </li>

                    <!-- Nav Item - Pages Collapse Menu -->
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Student" asp-action="Index">
                            <i class="fas fa-fw fa-school"></i>
                            <span>Students</span>
                        </a>
                    </li>
                    <!-- Divider -->
                    <hr class="sidebar-divider">
                    <!-- Sidebar Toggler (Sidebar) -->

                    <li class="nav-item">
                        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseEducation" aria-expanded="true" aria-controls="collapseEducation">
                            <i class="fas fa-fw fa-wrench"></i>
                            <span>Eğitim Bilgileri</span>
                        </a>
                        <div id="collapseEducation" class="collapse" aria-labelledby="headingEducation" data-parent="#accordionSidebar">
                            <div class="bg-white py-2 collapse-inner rounded">
                                <h6 class="collapse-header">Detay:</h6>
                                <a class="collapse-item" asp-controller="Education" asp-action="Index">Eğitim</a>
                                <a class="collapse-item" asp-controller="Level" asp-action="Index">Seviye</a>
                                <a class="collapse-item" asp-controller="Time" asp-action="Index">Zaman</a>
                                <a class="collapse-item" asp-controller="PaymentType" asp-action="Index">Ödeme Tipi</a>
                            </div>
                        </div>
                    </li>

                    <li class="nav-item">
                        <a asp-controller="DataQuality" asp-action="Index" class="nav-link">
                            <i class="fas fa-fw fa-database"></i>
                            <span>Data Kalitesi</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a asp-controller="DataSource" asp-action="Index" class="nav-link">
                            <i class="fas fa-fw fa-database"></i>
                            <span>Data Kaynağı</span>
                        </a>
                    </li>

                }
            }
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>
        </ul>
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">
            <!-- Main Content -->
            <div id="content">
                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>
                    <!-- Topbar Search -->
                    @*<div class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
                        <div class="input-group">
                            <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
                            <div class="input-group-append">
                                <button class="btn btn-primary" type="button">
                                    <i class="fas fa-search fa-sm"></i>
                                </button>
                            </div>
                        </div>
                    </div>*@
                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                        <li class="nav-item dropdown no-arrow d-sm-none">
                            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-search fa-fw"></i>
                            </a>
                            <!-- Dropdown - Messages -->
                            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
                                <div class="form-inline mr-auto w-100 navbar-search">
                                    <div class="input-group">
                                        <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
                                        <div class="input-group-append">
                                            <button class="btn btn-primary" type="button">
                                                <i class="fas fa-search fa-sm"></i>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </li>

                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">@ViewData["Username"]</span>
                                <img class="img-profile rounded-circle" src="https://source.unsplash.com/QAB-WJcbgJk/60x60">
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                                <a class="dropdown-item" asp-controller="User" asp-action="Settings">
                                    <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Settings
                                </a>
                                @*<a class="dropdown-item" href="#">
                                        <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                        Profile
                                    </a>
                                    <a class="dropdown-item" href="#">
                                        <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                                        Activity Log
                                    </a>*@
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Çıkış
                                </a>
                            </div>
                        </li>
                    </ul>
                </nav>
                <!-- End of Topbar -->
                <!-- Begin Page Content -->
                <div class="container-fluid">
                    <!-- Page Heading -->
                    <div class="d-sm-flex align-items-center justify-content-between mb-4">
                        <h1 class="h3 mb-0 text-gray-800">@ViewData["PageSubTitle"]</h1>
                        <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-download fa-sm text-white-50"></i> Generate Report</a>
                    </div>

                    @RenderBody()
                    <!-- /.container-fluid -->
                </div>
            </div>
            <!-- End of Main Content -->
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Eduface @DateTime.Now.Year</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->
        </div>
        <!-- End of Content Wrapper -->
    </div>
    <!-- End of Page Wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>
    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Çıkış</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Çıkmak istediğinize emin misiniz ?</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">İptal</button>
                    <a class="btn btn-primary" asp-controller="User" asp-action="LogOut">Çıkış</a>
                </div>
            </div>
        </div>
    </div>
    <!-- Bootstrap core JavaScript-->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- Core plugin JavaScript-->
    <script src="~/vendor/jquery-easing/jquery.easing.min.js"></script>
    <!-- Custom scripts for all pages-->
    <script src="~/js/sb-admin-2.min.js"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>